#creating a simple workflow
name: NodeJS Gitub Action

on: push

#another way to assign on push, for specific branches
# on:
#   push:
#     branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node

        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm install
      - name: Run Test
        run: npm test
          





